"""add_import_contract_v1

Revision ID: 4ed9e2bc20cc
Revises: 5bedddaa8059
Create Date: 2026-09-16 21:59:02.314314

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4ed9e2bc20cc'
down_revision: Union[str, Sequence[str], None] = '5bedddaa8059'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('accepted_answers', sa.Column('is_primary', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('questions', sa.Column('explanation', sa.Text(), nullable=True))
    op.add_column('questions', sa.Column('status', sa.String(), server_default='draft', nullable=False))
    op.add_column('questions', sa.Column('source_meta', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('questions', sa.Column('compound_group_id', sa.String(), nullable=True))
    op.add_column('questions', sa.Column('compound_type', sa.String(), nullable=True))
    op.add_column('questions', sa.Column('category', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('questions', 'category')
    op.drop_column('questions', 'compound_type')
    op.drop_column('questions', 'compound_group_id')
    op.drop_column('questions', 'source_meta')
    op.drop_column('questions', 'status')
    op.drop_column('questions', 'explanation')
    op.drop_column('accepted_answers', 'is_primary')
    # ### end Alembic commands ###
