"""Add status to quiz_versions

Revision ID: 5bedddaa8059
Revises: 96521d72efb4
Create Date: 2026-09-16 16:58:47.146569

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5bedddaa8059'
down_revision: Union[str, Sequence[str], None] = '96521d72efb4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('quiz_versions', sa.Column('status', sa.String(), server_default="draft", nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('quiz_versions', 'status')
    # ### end Alembic commands ###
