"""Add current_round_index to solo_attempts

Revision ID: 96521d72efb4
Revises: b0f2bcfb4fb2
Create Date: 2026-09-15 22:58:18.196659

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '96521d72efb4'
down_revision: Union[str, Sequence[str], None] = 'b0f2bcfb4fb2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('solo_attempts', sa.Column('current_round_index', sa.Integer(), server_default="0", nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('solo_attempts', 'current_round_index')
    # ### end Alembic commands ###
