"""Add solo attempts and answer records

Revision ID: b0f2bcfb4fb2
Revises: d357872fdc2b
Create Date: 2026-09-15 22:39:19.437318

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b0f2bcfb4fb2'
down_revision: Union[str, Sequence[str], None] = 'd357872fdc2b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('solo_attempts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('quiz_version_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('session_token', sa.String(length=64), nullable=False),
    sa.Column('timer_mode', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('current_question_index', sa.Integer(), nullable=False),
    sa.Column('total_score', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['quiz_version_id'], ['quiz_versions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_solo_attempts_id'), 'solo_attempts', ['id'], unique=False)
    op.create_index(op.f('ix_solo_attempts_session_token'), 'solo_attempts', ['session_token'], unique=True)
    op.create_index(op.f('ix_solo_attempts_user_id'), 'solo_attempts', ['user_id'], unique=False)
    op.create_table('answer_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('attempt_id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('submitted_text', sa.String(), nullable=False),
    sa.Column('is_correct', sa.Boolean(), nullable=False),
    sa.Column('points_awarded', sa.Integer(), nullable=False),
    sa.Column('answered_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['attempt_id'], ['solo_attempts.id'], ),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_answer_records_attempt_id'), 'answer_records', ['attempt_id'], unique=False)
    op.create_index(op.f('ix_answer_records_id'), 'answer_records', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_answer_records_id'), table_name='answer_records')
    op.drop_index(op.f('ix_answer_records_attempt_id'), table_name='answer_records')
    op.drop_table('answer_records')
    op.drop_index(op.f('ix_solo_attempts_user_id'), table_name='solo_attempts')
    op.drop_index(op.f('ix_solo_attempts_session_token'), table_name='solo_attempts')
    op.drop_index(op.f('ix_solo_attempts_id'), table_name='solo_attempts')
    op.drop_table('solo_attempts')
    # ### end Alembic commands ###
